// Single source of truth for all three concepts.
// To add a project: append one object to PROJECTS — every layout picks it up.
window.SITE = {
  name: 'Ai Work',
  kicker: 'Ai Work',
  intro: '用 AI 把腦袋的想法做出來。',
  email: 's923446@gmail.com',
  socials: [
    ['Website', 'https://weilee01.com/'],
    ['Instagram', 'https://www.instagram.com/c.w._lee/'],
    ['LinkedIn', 'https://www.linkedin.com/in/chienweilee/'],
    ['Facebook', 'https://www.facebook.com/taiwankiss1'],
  ],
  toolkit: ['Claude', 'Gemini', 'ChatGPT', 'Higgsfield', 'Blender', 'Photoshop', 'Illustrator', 'Premiere Pro', 'Figma'],
};

window.PROJECTS = [
  {
    key: 'dashboard',
    title: 'My Dashboard',
    tag: 'Data',
    sub: 'Orbit-style life dashboard',
    year: '2026',
    color: '#9b8cff',
    color2: '#4fc3ff',
    bg: '#0f0c1d',
    one: '關於我學習與訓練的軌跡',
    // longer context shown on the Numbers (why) and Gallery (process) chapters
    why: '跑步、騎車、英文和 AI 使用紀錄散在不同平台，每次都要逐一登入比對，很難看出時間到底花去哪、有沒有在蹉跎。',
    process: '用 Connector 串接 Strava、Santa、Claude，統一各平台的資料格式與更新頻率，再把近 30 天畫成同心軌道，反覆調整資訊密度與可讀性。',
    steps: [
      ['問題', '數據散在 4 個平台'],
      ['做法', 'Connector 串接 Strava · Santa · Claude'],
      ['成果', '一眼看完 30 天時間分配'],
    ],
    stats: [['4', '資料來源'], ['30', '天滾動視窗'], ['1', '個畫面']],
    tools: ['Claude', 'Strava', 'Santa'],
    link: 'https://taiwankiss.github.io/wei-dashboard/',
    shots: ['dashboard-1', 'dashboard-2'],
    mobile: 'dashboard-m',
    video: 'dashboard',
  },
  {
    key: 'peaks',
    title: '100 Peaks',
    tag: 'Data',
    sub: 'Taiwan 百岳 challenge map',
    year: '2026',
    color: '#ff8a3d',
    color2: '#8fcf7a',
    bg: '#070b09',
    one: '回放每一趟百岳單攻',
    why: '高山環境充滿變數，每一趟的路線、時間與補給都值得留下，下一次出發才更有把握，也能回頭看看走過的路。',
    process: '整理 Strava、健行筆記的 GPX 與 Google Sheet 打卡紀錄，用地形圖磚把路線做成 3D 等高線動畫；沒有 GPS 的幾座，改用 OpenStreetMap 步道推算。',
    steps: [
      ['問題', 'GPX、照片、試算表各放各的'],
      ['做法', 'GPX 轉 3D 等高線路線動畫'],
      ['成果', '17 座百岳，8 趟可回放'],
    ],
    stats: [['17', '座百岳'], ['217.1', 'km 總里程'], ['19,434', 'm 總爬升']],
    tools: ['Claude', 'Strava', 'Google Sheets'],
    link: 'https://100-peaks.pages.dev/',
    shots: ['peaks-1', 'peaks-3', 'peaks-2', 'peaks-4'],
    mobile: 'peaks-m',
    video: 'peaks',
  },
  {
    key: 'shopping',
    title: 'Shopping Insight',
    tag: 'Data',
    sub: 'Nine years of Taobao orders',
    year: '2026',
    color: '#4f7cff',
    color2: '#edeae4',
    bg: '#09090a',
    one: '九年半的淘寶消費，一台購物車看完',
    why: '在淘寶買了九年半，想知道錢到底花去哪，以及生活的改變怎麼反映在購物清單上。',
    process: '用 Apps Script 整理並分類 732 筆訂單，在 Blender 建出購物車模型，再用 Three.js 讓它隨捲動旋轉、拆解、切層，串起 8 個章節。',
    steps: [
      ['問題', '9 年淘寶訂單堆在試算表'],
      ['做法', 'Blender 購物車 + Three.js 捲動拆解'],
      ['成果', '8 個章節看完 732 筆訂單'],
    ],
    stats: [['732', '筆訂單'], ['895', '個品項'], ['428,904', 'NT$ 總消費']],
    tools: ['Claude', 'Blender', 'Google Sheets'],
    link: 'https://shopping-insight.s923446.workers.dev/',
    shots: ['shopping-1', 'shopping-2', 'shopping-3', 'shopping-4', 'shopping-5'],
    mobile: 'shopping-m',
    video: 'shopping',
  },
  {
    key: 'campaign',
    title: 'Train Hard',
    tag: 'Web',
    sub: 'Scroll-driven campaign page',
    year: '2026',
    color: '#ff9e5a',
    color2: '#5aa0ff',
    bg: '#0d0b0a',
    one: '持續滾動推進訓練的一天',
    why: '一直想試試 scrollytelling 的華麗效果，就把喜歡的跑步、騎車、登山組成一個品牌活動頁，讓人看完就想出門訓練。',
    process: '先用 ChatGPT 生成三種運動的設定圖，再用 Higgsfield 渲染影片；原本一格畫面對應一次滾動效果不好，改成滑一次播一段，轉場更順。',
    steps: [
      ['問題', '想做一次 scrollytelling'],
      ['做法', 'ChatGPT 設定圖 → Higgsfield 生成影片'],
      ['成果', '滑一次播一段，數據 UI 同步推進'],
    ],
    stats: [['3', '種運動'], ['100%', 'AI 生成影片'], ['∞', 'scroll']],
    tools: ['Claude', 'Higgsfield', 'ChatGPT'],
    link: 'https://train-hard.s923446.workers.dev/',
    shots: ['campaign-1', 'campaign-2', 'campaign-3', 'campaign-4'],
    mobile: 'campaign-m',
    video: 'campaign',
    // recorded without the site's dot texture; the page lays the dots back on in CSS (much smaller files)
    halftone: true,
  },
];

// About me: sits in the orbit like any project and has its own page.
// `showcase` adds a chapter with the desktop + mobile recordings side by side.
window.ABOUT = {
  key: 'about',
  title: 'About me',
  tag: 'About',
  sub: 'Visual Designer / Design Manager',
  year: '2026',
  color: '#f24e1e',
  one: '關於我的履歷',
  why: '履歷不只拿來閱讀，也希望它本身就是一件能被欣賞的設計作品，在一疊文字履歷裡更有辨識度。',
  process: '用 Adobe Firefly 把大頭照生成動態影像，再和 Claude Code 以 vibe coding 反覆調整排版、字體與動態節奏。',
  steps: [
    ['2019—26', '悠勢科技 · Design Manager'],
    ['2018—19', '華生基因 · Visual Designer'],
    ['2014—18', '貝殼放大 · Visual Designer'],
  ],
  stats: [['10+', '年設計經驗'], ['3', '個產業深耕'], ['7', '項核心技能']],
  tools: ['Claude', 'Adobe Firefly'],
  link: 'https://taiwankiss.github.io/resume/',
  shot: 'resume-1',
  shots: ['resume-1', 'resume-2'],
  mobile: 'resume-m',
  video: 'resume',
  showcase: true,
};
